name: macOS

on:
  push:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  mac-build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build macOS
      run: ./make.sh
