name: Windows

on: # [push, pull_request]
  push:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build Windows
      shell: cmd
      run: .\winmake.bat
